# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Lint with flake8
      run: |
        poetry run flake8 timr/ --statistics
    - name: build package 
      run: |
        poetry check
        poetry show
        poetry build
    - name: publish package (pypi test)
      env: 
        PIPY__TOKEN__: ${{ secrets.PIPY__TOKEN__ }}
      run: |
        poetry check
        poetry show
        poetry publish --username __token__ --password ${PIPY__TOKEN__}
